version: "3"

networks:
  my_shared_network: {}

services: 
  # First service (container): the server.
  mysimbdp-server:
    container_name: server
    build:
      context: ./mysimbdp-server/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - my_shared_network
  
  # Second service (container): the database.
  mysimbdp-coredms:
    container_name: db
    image: cassandra:latest
    volumes:
      - ./mysimbdp-coredms/db:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=mysimbdp-coredms-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks: 
      - my_shared_network
    depends_on: 
      - mysimbdp-server
