version: "3.0"


services:

  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    volumes:
      - #./mysimbdp-coredms/db:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=mysimbdp-coredms-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1


  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181:2181"

      
  # This Kafka container is available in kafka:9092 if your consumer/producer is also in a docker container, 
  # or localhost:9093 if your application is running locally.
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "test_topic:2:1"  # Create a test topic with 2 partitions and 1 replica.
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
