version: "3.0"

services:
  #-------------------------------------------------------------------------------
  # Cassandra database
  #-------------------------------------------------------------------------------
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    volumes:
      - ./mysimbdp-coredms/db:/var/lib/cassandra/data/mysimbdp_coredms
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=mysimbdp-coredms-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks:
      - shared-network

  #-------------------------------------------------------------------------------
  # RabbitMQ Message Broker
  #-------------------------------------------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
        - 5672:5672  #default port for message broker
        - 15672:15672  #default port for RabbitMQ GUI
    volumes:
        - ./mysimbdp-databroker/rabbitmq:/var/lib/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shared-network

  #-------------------------------------------------------------------------------
  # Flink
  #-------------------------------------------------------------------------------
  flink-jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - shared-network

  flink-taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink-jobmanager
    command: taskmanager
    links:
      - "flink-jobmanager:flink-jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - shared-network

networks:
  shared-network: