version: "3"

networks:
  my_shared_network: {}

services: 
  mysimbdp-coredms:
    container_name: db
    image: cassandra:latest
    volumes:
      - ./mysimbdp-coredms/db:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=mysimbdp-coredms-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks: 
      - my_shared_network

  rabbitmq:
      image: rabbitmq:3
      container_name: rabbit
      hostname: rabbit
      ports:
          - 5672:5672
          - 15672:15672
      networks: 
      - my_shared_network
      volumes:
          - ./mysimbdp-databroker/rabbitmq:/var/lib/rabbitmq
      environment:
          RABBITMQ_ERLANG_COOKIE: cluster_cookie
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
          RABBITMQ_DEFAULT_VHOST: /
